// Package db owns opening the SQLite database and applying migrations.
// Query code generated by sqlc lives in the sibling gen/ package once
// Phase 1 writes the schema and queries; this file is schema-agnostic.
package db

import (
	"database/sql"
	"embed"
	"fmt"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// Open opens (creating if absent) the SQLite file at path and applies every
// pending migration embedded in this binary. A single call at startup is
// the whole migration story — no separate CLI step to run on the VM.
func Open(path string) (*sql.DB, error) {
	conn, err := sql.Open("sqlite", path+"?_pragma=foreign_keys(1)")
	if err != nil {
		return nil, fmt.Errorf("ouverture sqlite: %w", err)
	}
	// SQLite has a single writer; a large pool just serializes anyway and
	// risks SQLITE_BUSY under goose's own migration transaction.
	conn.SetMaxOpenConns(1)

	goose.SetBaseFS(migrationsFS)
	if err := goose.SetDialect("sqlite3"); err != nil {
		return nil, fmt.Errorf("dialecte goose: %w", err)
	}
	if err := goose.Up(conn, "migrations"); err != nil {
		return nil, fmt.Errorf("migrations: %w", err)
	}
	return conn, nil
}
